Add new properties, new characteristics, Generic Property messages
SilvairGit/python-bluetooth-mesh-messages pull request #4
Opened 2024-08-22 13:24 UTC by wiktorzbroja-silvair

2024-08-27 09:29 UTC, bartekbartnicki-silvair approved these changes
- checked with spec
- all GenericPropertyOpcode tested
- not all Properties tested by UT (IMO, we don't want check all of them, I don't see added value of UT which check all properties IDs - we should check it manually by comparing with specification)
- we have discuss with Wiktor about validating if values of properties are valid:
  - From our perspective (testers) in same cases we want to prepare invalid message
  - In other place in bluetooth_mesh we do not validate it. It could be introduce in future after decision that we want do it globally and after agree how we want to do it.
  - In FW tests we could want validate if FW do not send invalid values of properties. According "Explicit is better than implicit" I prefer to write tests where we explicit check value of property than to excepting exception from bluetooth_mesh.

2024-08-27 09:30 UTC, bartekbartnicki-silvair commented
@michallowasrzechonek-silvair From my perspective ready to merge and publish

2024-09-05 10:14 UTC, kamiljanowski-silvair commented
Please, add payloads that can be created to `test_capnproto.py` file

2024-09-05 10:15 UTC, kamiljanowski-silvair requested changes
add tests with example payloads (the best with different msg format which will be used in Silvair Platform) to test_capnproto.py

2024-09-10 09:39 UTC, michallowasrzechonek-silvair approved these changes
LGTM!

2024-09-11 10:30 UTC, kamiljanowski-silvair commented on bluetooth_mesh/messages/generic/property.py
> +PropertyStatus = Struct(
This shall not be removed?

2024-09-11 10:56 UTC, kamiljanowski-silvair approved these changes

2024-09-11 11:00 UTC, wiktorzbroja-silvair commented on bluetooth_mesh/messages/generic/property.py
> +PropertyStatus = Struct(
True

2024-09-11 12:40 UTC, kamiljanowski-silvair requested changes
Please, clean commit history. I prefer to have 3 commits:

1) Add Generic Property messages + tests
2) reformat other payloads in test_capnproto
3) Black + isort reformat

2024-09-11 13:07 UTC, kamiljanowski-silvair approved these changes
Good job :)

2024-09-11 13:13 UTC, merged